### ISSUE TITLE
Problem with dot access

### ISSUE THREAD

**Issue by jmansion** [stackbuilders/stache#15]
In the program below, I get:

Hi, John Doe! You have:
  * pen () (blue)

Note that:
 - {{name.first}} {{name.last}} DID work
 - {{atts.colour}} did NOT work, while {{#atts}}{{colour}}{{/atts}} DID work

I think {{atts.colour}} should be equivalent to {{#atts}}{{colour}}{{/atts}}.

---

{-# LANGUAGE OverloadedStrings #-}

module Main (main) where

import Data.Aeson
import Data.Text
import Text.Megaparsec
import Text.Mustache
import qualified Data.Text.Lazy.IO as TIO

main :: IO ()
main = do
  let res = compileMustacheText "foo"
        "Hi, {{name.first}} {{name.last}}! You have:\n{{#things}}\n  * {{type}} ({{atts.colour}}) ({{#atts}}{{colour}}{{/atts}})\n{{/things}}\n"
  case res of
    Left err -> putStrLn (parseErrorPretty err)
    Right template -> TIO.putStr $ renderMustache template $ object
      [ "name"   .= object [ "first" .= ("John" :: Text), "last" .= ("Doe" :: Text) ]
      , "things" .= [ object [ "type" .= ("pen" :: Text), "atts" .= object [ "colour" .= ("blue" :: Text)]] ]
      ]

**Comment by mrkkrp** [comment]
I can reproduce this.

**Comment by mrkkrp** [comment]
Thank you for opening the issue, the problem is resolved now. I'll bump version and upload to Hackage once the Travis check finishes.

**Comment by mrkkrp** [comment]
The fixed version (0.1.6) is available on Hackage.
