### ISSUE TITLE
Non-optional partials

### ISSUE THREAD

**Issue by ralphmorton** [stackbuilders/stache#16]
Although the mustache spec states "If the named partial cannot be found, the empty string SHOULD be used instead, as in interpolations.", this is not always desirable behavior. It would be helpful to have an alternate rendering mode in which missing partials result in an error (perhaps parameterizing the underlying code over some kind of functor to make this possible?).

If this is something you would consider merging, I would be happy to submit a PR.

**Comment by mrkkrp** [comment]
I like the idea, just let me think of a way to add this with minimal conflicts for users downstream.

**Comment by ralphmorton** [comment]
Great, thanks! :+1:

**Comment by mrkkrp** [comment]
I think we can proceed as following:

1. Add `renderMustache'` to `Text.Mustache.Render` which is the same as `rederMustache`, but throws an exception (add it too, perhaps to `Text.Mustache.Types`) when a key is not found. Explain the difference in docs properly.

2. The exception should at least include info about which key was missing.

3. Add a flag that says whether we want to throw or not to `RenderContext`. `runRender` will get the flag as argument.

4. Now with the flag following us everywhere, make sure that missing keys cause an exception only when the flag says we should throw.

5. Add new tests proving that the new functio `renderMustache` throws when it should and what it should.

Once this is done, I'll review, update the `CHANGELOG.md` file and publish a new release.

**Comment by ralphmorton** [comment]
:+1: sounds fair, I will come back with a patch.

**Comment by mrkkrp** [comment]
Have you started on this already? I think we could just make this behaviour default and release 0.2.0 version. I can spend some time today making the changes.

**Comment by ralphmorton** [comment]
No, I am very pressed for time this week (hamster wheel :wink: ). I was planning to do it tomorrow but if you have the time that would be amazing!

**Comment by mrkkrp** [comment]
OK then, I'll do it. Indeed in such a correct language we should not "hide" things like this, because missing values are almost always a mistake. If user needs to render empty string instead, he/she can pass an empty string explicitly.

**Comment by mrkkrp** [comment]
Implemented. This made me comment out a couple of tests from the official spec that test that missing values are rendered as empty stirngs, but I think we don't have to follow the spec where it's broken by design. Explicit is better than implicit :-D

**Comment by mrkkrp** [comment]
Yay, version 0.2.0 is on Hackage now!

**Comment by ralphmorton** [comment]
Nice, thanks for implementing! This will help us a lot.

**Comment by mrkkrp** [comment]
@ralphmorton Heads up, this will be reverted in 0.3.0, because it does not play very nicely with Mustache ways of doing things. For example `{{# my_thing }}Here it is: {{ . }} {{/ my_thing}}` throws if `my_thing` is missing, while it should be just skipped. This feature also made `stache` violate the official spec, which is not good for a library that claims to implement Mustache templates (not Mustache-like templates). Your options are either not to upgrade to version 0.3.0 when it's out, but it's not very future-proof, or fork. Or better yet add unit tests for your rendering functions, which is of course the correct solution to this, but takes time.

**Comment by mrkkrp** [comment]
#21 reverts the feature.
