### ISSUE TITLE
Variant of renderMustache which collects errors

### ISSUE THREAD

**Issue by RyanGlScott** [stackbuilders/stache#23]
(Originally from https://github.com/phadej/microstache/issues/3.)

Currently, `renderMustache` does not give any indication that substitution errors have occurred (other than a return value of `""`, but I dislike relying on stringly typed programming practices). This has caused confusion at least once: see https://github.com/bos/criterion/issues/127. It would be convenient to have a variation on `renderMustache` that also gives error messages, similarly to how [`checkedSubstitute`](http://hackage.haskell.org/package/mustache-2.2.3/docs/Text-Mustache-Render.html#v:checkedSubstitute) from the `mustache` library does this.

**Comment by RyanGlScott** [comment]
The `microstache` version of this is [`renderMustacheW`](https://github.com/phadej/microstache/pull/4).

**Comment by juanpaucar** [comment]
@mrkkrp what do you think?

**Comment by mrkkrp** [comment]
That's a good idea, we should probably add it in the next version (probably 1.0.0, pending Megaparsec 6).

**Comment by phadej** [comment]
@mrkkrp, let's have discussion about the issue here.

Porting the `microstache` patches should be trivial, as rendering part is essentially the same.

**Comment by mrkkrp** [comment]
Yep, I intend to port the feature from phadej/microstache#4 as soon as I have the time.
