### ISSUE TITLE
Template names behave differently between compileMustacheFile and compileMustacheDir

### ISSUE THREAD

**Issue by csasarak** [stackbuilders/stache#40]
This may or may not be a bug. I found that when I do something like:

```haskell
compileMustacheFile "template_dir/filename.txt.mustache"
```
and render, stache works. However, when I do:

```haskell
compileMustacheDir (PName "filename.txt.mustache") "template_dir/"
```
and render, the rendering fails. I eventually figured out I needed to write:

```haskell
compileMustacheDir (PName "filename.txt") "template_dir/"
```

This could just be because I'm not familiar enough with mustache templates, but it did trip me up. The solution could either be making the library less sensitive to names, or documenting the difference.

**Comment by mrkkrp** [comment]
I added a note about this to documentation of `compileMustacheDir`. Thanks for reporting it!
