### ISSUE TITLE
Using stache as an HTML template system for web apps

### ISSUE THREAD

**Issue by manuca** [stackbuilders/stache#46]
Hi, I've been looking at stache as an option for HTML templating in a small Scotty app. I'd like to be able to use some kind of common `.mustache` layout and then embed rendered sections into the body of that layout.

Something like:

```
<!doctype html>
<html>
  <head>
    <title>Mustache layout</title>
  </head>

  <body>
    {{ sectionContent }}
  </body>
</html>
```

Where `sectionContent` is the output from a rendered section. 

Is this a valid use case for stache or should I go with a different option? 

I'm also trying to wrap my head around how `compileMustacheDir` would enter into play in this situation as from what I've seen each compiled directory is treated as a single template unit, so I'm not sure how I would organize a general layout + specific section templates in an app.

I'm pretty novice in Haskell so any orientation will be helpful.

Thanks!

**Comment by mrkkrp** [comment]
That's what I do on my [site](https://github.com/mrkkrp/markkarpov.com).

**Comment by manuca** [comment]
> That's what I do on my [site](https://github.com/mrkkrp/markkarpov.com).

Interesting, will research your site @mrkkrp.
Thanks

**Comment by mrkkrp** [comment]
Closing for now.
